GET http://localhost:3000/api/v1/users

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
 "fullname": "admin",
 "username": "admin",
 "password": "admin",
 "email": "budiprayoga5103@gmail.com",
 "phone": "08189834789",
 "role_id": "045a745d-fb10-4976-bb7d-883567a3e8c9"
}

###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
 "username": "admin",
 "password": "admin"
}

###
GET http://localhost:3000/api/v1/logout

#-------------------------------- roles ------------------------------------------#

###
GET http://localhost:3000/api/v1/roles


###
POST http://localhost:3000/api/v1/roles
Content-Type: application/json

{
 "name": "wdwd"
}

###
PATCH http://localhost:3000/api/v1/roles/0986754b-94f7-44e0-8c91-7da7c5597ddf
Content-Type: application/json

{
 "name": "da"
}

###
DELETE http://localhost:3000/api/v1/roles/ecc3e928-cc9c-47e9-930e-7e67be714dd1


#-------------------------------- Permissions ------------------------------------------#

###
GET http://localhost:3000/api/v1/permissions/47820a5d-9398-457d-bef6-43d79e9496ca

###
PATCH http://localhost:3000/api/v1/permissions/045a745d-fb10-4976-bb7d-883567a3e8c9
Content-Type: application/json

{   
  "listModules": [
    {
      "id": 1,
      "canRead": 1,
      "canCreate": 1,
      "canUpdate": 1,
      "canDelete": 1
    },
    {
      "id": 2,
      "canRead": 1,
      "canCreate": 1,
      "canUpdate": 1,
      "canDelete": 1
    },
    {
      "id": 3,
      "canRead": 1,
      "canCreate": 1,
      "canUpdate": 1,
      "canDelete": 1
    }
  ]
}
